### PR TITLE
Updated compileViews() method to search for blade template files recursively

### PR DESCRIPTION
**Pull request by bart**
This is necessary for a multi-level view folder structure

### CODE REVIEW

**Comment by shaggyz** [comment]
Hi, thanks! Can you review this? The package already supports multi-level folder structure for views:

```php
// config/laravel-gettext.php
'source-paths' => array(
    '../resources/views' 
)
```
It's valid for **view/foo** and **view/foo/bar**, etc.

Also, tests are failing with this PR.

**Comment by bart** [comment]
Unfortunately "../resources/views" does not include files from the 2nd level. It just includes resources/views/* and resources/views/*/* but not more. This is caused by the regex in the $fs->glob method call. But I will check the test asap!

**Comment by bart** [comment]
Fixed compileViews unit test method but testTranslations testing method still fails (But it fails in the original master, too)

**Comment by shaggyz** [comment]
Ok, let me see what happens with this, because second level directories are working on 1.x and 2.x version.

**Comment by bart** [comment]
@shaggyz I tried it out and it did not work before due to the glob() method which is not recursive.

**Comment by shaggyz** [comment]
@bart Merged! Thank you and sorry for the delay.

**Comment by bart** [comment]
No problem, thanks for merging!

**Pull request merged**
