### PR TITLE
Update to Laravel 5.4

### LINKED ISSUE #110: Not compatible with Laravel 5.4
Hi! I'm using your package and wanted to upgrade to Laravel 5.4 that just released. There's a change where the app->share() method has been removed and instead you should use singleton(). I cannot myself make a PR as I don't know how to fix it. I'm hoping you can :)

    LaravelGettextServiceProvider.php
    $this->app['laravel-gettext'] = $this->app->share(function ($app) use ($configuration) {

### PR DESCRIPTION
**Pull request by Belphemur**
Share method doesn't exists anymore, need to use the singleton (which does the same).

Following https://laravel.com/docs/5.4/upgrade

Fixes #110

### CODE REVIEW

**Comment by Belphemur** [comment]
@shaggyz you have a problem with your test for PHP 5.6, you're using a class for it that doesn't exists.

The test for PHP 7.0 passed without problem

**Comment by digitop** [comment]
For me it's working with a fresh Laravel 5.4 install after doing these steps:

- Copied the whole file content to my file
- Updated the 43. row to this: `$this->app->singleton('laravel-gettext', function ($app) use($configuration) {` because the `use($configuration) ` was missing.
After this it's working for me.

**Comment by Belphemur** [comment]
I don't have that issue with this patch

But laravel created now the function __ that override the one in this package.

I'm going to rename it __i (for internationalisation)

**Comment by CedNet** [comment]
Renaming to__() to_i() will make POEdit not work and hence making this package pointless. Doesn't it?

**Comment by Belphemur** [comment]
__() is already a made up alias that is not standard to gettext/poedit. 

Only_() and_n() are the default recognized without configuration. 

This packet is adding its own keyword to the list for poedit to recognize it, I only followed the same syntax. 

You can configure the keywords in the configuration file by adding _i() to the list and then regenerate your gettext file with the update command. 

You can see in the header of the file the keywords section containing the keywords that poedit will look for. 

I had no choice but changing the alias since laravel has precedence on this packet. 

⁣Sent from BlueMail ​

**Comment by thomasbilk** [comment]
I ran into another issue with Laravel 5.4. In `SessionHandler` the call on `Session` should be changed from `set` to `put`. This is described in the [Uprage Guide](https://laravel.com/docs/5.4/upgrade) under "Session".  @Belphemur can you add that to this PR?

**Comment by Belphemur** [comment]
@thomasbilk the code on the master branch is already using `put` instead of `set`

**Comment by TullariS** [comment]
@Belphemur here is a thought:

We could of course include the helper file to bootstrap/autoload.php but it seems that PHPUnit doesn't load it, so what if instead of replacing __(), we replace what Laravel __() does?

as per the source:
function __($key = null, $replace = [], $locale = null)
{
return app('translator')->getFromJson($key, $replace, $locale);
}

It seems __() only serves as a wrapper to Illuminate\Translation\Translator.

I believe the solution might be in replacing Illuminate\Translation\TranslationServiceProvider with a custom one.

As for making a new Translator->getFromJson(), the number of parameters sent by Laravel's __() is set to 3, but that can be fixed by running debug_backtrace(0,2) and fetching the original number of arguments.

Of course what really needs to happen is for Laravel to provide a proper way to override helpers but this could solve the problem in the meantime.

Hope this helps.

**Comment by Belphemur** [comment]
Sound good on paper but to replace the translation provider of laravel would mean having to manage ourself the validation message and the way they are used as for now it's managed by that provider. 

I don't know if it worth so much as to simply ask the dev to change the alias they are using since after all you have already to update your code. 

I've done it simply by using the refactoring features of phpstorm by renaming the __ to_i

**Comment by CedNet** [comment]
I talked with the dev for Laravel about the decision to use __() in Laravel when __() is also used by for example WordPress and such. I don't like the idea of taking on a well known "standard" and implementing it as your own. It can cause major need for refactoring to many using the package / framework whatever. 

For now, I guess you'll have to tag a breaking change version of your package and some refactoring needs to be made. I can't upgrade to Laravel 5.4 until this is resolved. so... =)

**Comment by afontcu** [comment]
Any progress on that?

**Comment by Belphemur** [comment]
Since I don't have any answer from the main developer.

I made a fork and published it on Packagist: 
https://packagist.org/packages/belphemur/laravel-gettext

The tag 5.0.0 is for laravel 5.4, tested and working.

**Comment by bart** [comment]
@shaggyz Would you please merge this one?

**Comment by cojocaru3** [comment]
Can anyone confirm 100% compatibility with Laravel 5.4 ?

**Comment by Belphemur** [comment]
Because I never received any answer from the owner of the repo, I close my PR.

# Package
https://packagist.org/packages/belphemur/laravel-gettext

# Repository
https://github.com/Belphemur/laravel-gettext

# How to upgrade
If you're upgrading from the 4., the one for Laravel 5.3., you need to refactor your usage of the __ method.

Laravel now use this method for their own translation. You now need to use _i instead and add this keyword in the configuration file of Laravel-Gettext:

Also, if you're using Symfony as your backend, you can add the _s method. It's made to use the full feature set of Symfony plurals syntax.
```php
  /**
     * The keywords list used by poedit to search the strings to be translated
     *
     * The "_", "__" and "gettext" are singular translation functions
     * The "_n" and "ngettext" are plural translation functions
     * The "dgettext" function allows a translation domain to be explicitly specified
     *
     * "__" and "_n" and "_i" and "_s" are helpers functions @see \Xinax\LaravelGettext\Support\helpers.php
     */
    'keywords-list' => ['_', '__', '_i', '_s', 'gettext', '_n:1,2', 'ngettext:1,2', 'dgettext:2'],;
```

**Comment by layershifter** [comment]
@cojocaru3 Yep, works in my production apps and I recommend to switch to the @Belphemur's fork.

**Pull request closed without merging**
